# Generated by Django 3.0.5 on 2020-04-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(default='Профиль', on_delete=django.db.models.deletion.PROTECT, to='usersproj.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('page_num', models.IntegerField(default=0)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersproj.Shelf')),
            ],
        ),
    ]
