# Generated by Django 3.0.5 on 2020-04-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersproj', '0002_book_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='profile',
            field=models.ForeignKey(default='Профиль', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
