# Generated by Django 3.0.5 on 2020-05-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersproj', '0007_auto_20200526_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='profile_avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='profile_avatar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='usersproj.Gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name_gallery',
            field=models.CharField(default='Мои Фотографии', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_in_gallery',
            field=models.ForeignKey(default='photo_in_gallery', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
