# Generated by Django 3.0.5 on 2020-05-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersproj', '0010_auto_20200526_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo_in_gallery',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
