# Generated by Django 3.0.5 on 2020-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersproj', '0014_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
