# Generated by Django 3.0.5 on 2020-06-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersproj', '0015_book_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('page_num', models.IntegerField(default=0)),
                ('book', models.FileField(blank=True, null=True, upload_to='books/')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersproj.ShelfAdmin')),
            ],
        ),
    ]
