# Generated by Django 3.0.5 on 2020-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersproj', '0016_bookadmin_shelfadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookadmin',
            name='shelf',
        ),
        migrations.AddField(
            model_name='bookadmin',
            name='shelf',
            field=models.ManyToManyField(blank=True, to='usersproj.Shelf'),
        ),
    ]
